apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "kikkersqlpad.fullname" . }}
  labels:
    app: {{ include "kikkersqlpad.name" . }}
    chart: {{ include "kikkersqlpad.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kikkersqlpad.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: {{ include "kikkersqlpad.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          volumeMounts:
{{- if .Values.persistence.enabled }}
            - mountPath: /var/lib/sqlpad
              name: {{ .Release.Name }}-volume
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
{{- if .Values.persistence.enabled }}
        - name: {{ .Release.Name }}-volume
          persistentVolumeClaim:
            claimName: {{ template "kikkersqlpad.fullname" . }}
{{- end }}
