apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kikker-maildev
  namespace: kikkeruat
spec:
  gateways:
  - kikker-gateway-cloud
  hosts:
  - 'demo.kikker.nl'
  http:
  - match:
    - uri:
        prefix: "/mail"   
    route:
    - destination:
        host: kikkermaildev
        port:
          number: 80