apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kikker-maildev-smtp
  namespace: kikkeruat
spec:
  gateways:
  - kikker-gateway-cloud
  hosts:
  - 'demo.kikker.nl'
  http:
  - match:
    - uri:
        prefix: "/smtpmail"   
    rewrite:
      uri: "/"
    route:
    - destination:
        host: kikkermaildev
        port:
          number: 25