apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kikkeromnidb
  namespace: kikkeruat
spec:
  gateways:
  - kikker-gateway-cloud
  hosts:
  - 'demomysqldb.kikker.nl'
  http:
  - match:
    - uri:
        prefix: "/"  
    route:
    - destination:
        host: kikkeromniob-kikkeromnidb
        port:
          number: 8080