apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kikkersqlpad
  namespace: kikkeruat
spec:
  gateways:
  - kikker-gateway-cloud
  hosts:
  - 'demodb.kikker.nl'
  http:
  - match:
    - uri:
        prefix: "/"  
    route:
    - destination:
        host: kikkersqlpad
        port:
          number: 3000